<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * @file
 * The Elog module main file.
 */


function elog_node_insert(EntityInterface $entity) {

  //ksm($entity->getEntityTypeId());
  //ksm($entity->bundle());

}

function elog_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {

  //ksm($entity->toArray());
  //ksm($entity->bundle());

}