<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * @file
 * The Elog module main file.
 */


/**
 * Implements hook_ENTITY_TYPE_view().
 *
 * @inheritdoc
 */

function elog_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {


}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * @inheritdoc
 */

function elog_node_presave(Drupal\node\NodeInterface $node){

    // Ensure that all nodes have a lognumber field assigned when they get saved.
    if ($node->bundle() == 'logentry' && $node->isNew() ) {
        // Even if we know the node isNew and being saved for the first time, we might already
        // have a lognumber assigned from the LogNumberDefaultWidget if the node is being created
        // via the web form.  When the node is created programmatically, and no form widget
        // has been invoked, the assignment below will get invoked.
        if ($node->get('field_lognumber')->isEmpty()){
            $logNumberService = \Drupal::service('elog.lognumber');
            $node->set('field_lognumber', $logNumberService->nextLogNumber() );
        }
    }
}


